### ISSUE TITLE
3D line fit using SVD

### ISSUE THREAD

**Issue by murkle** [zalo/zalo.github.io#5]
re https://zalo.github.io/blog/line-fitting/#

> There are a variety of iterative solutions available, but they often depend on an operation called the Singular Value Decomposition or SVD

I'm  trying to collect examples of SVD use here
https://www.geogebra.org/m/Sc6ybzdu

This one
https://www.geogebra.org/m/Sc6ybzdu#material/hmTzuJ2d

uses the method from the first answer here I think
https://stackoverflow.com/questions/2298390/fitting-a-line-in-3d

which suggests it's a closed form problem with SVD, not iterative. Do the iterative methods calculate something better?

Thanks for your help, just trying to understand SVD a little better :)

Here's the rough code from my example for reference:

```
U=svd(1)
Σ=svd(2)

singularVectorForLargestSingularValue=Element(Transpose(U),b)
singularVectorForSmallestSingularValue=Element(Transpose(U),a)

directionVector= (singularVectorForLargestSingularValue(1),singularVectorForLargestSingularValue(2),singularVectorForLargestSingularValue(3))

bestFitLine = Line(Centroid,directionVector)
```

**Comment by jselstad** [comment]
The SVD itself is iterative (in 3D and beyond):
https://en.wikipedia.org/wiki/Singular_value_decomposition#Calculating_the_SVD

(its implementation is also usually hundreds of lines of matrix math, which is why I try to avoid it in game engines when possible)

SVD also often computes more terms than you necessarily need; Eigen (a popular C++ matrix library) allows you to specify computing a "Full" version and a "Thin" version of each output, allowing you to save on the time it takes to compute.   Power Iteration only gives you the largest eigenvector in the data, so you're hypothetically not doing extra work.

That said, it's unclear whether an adhoc implementation of power iteration will be faster than a fully SIMD vectorized implementation of SVD with "Thin" outputs enabled.

**Comment by murkle** [comment]
Thanks, that's very interesting!

We use Apache Commons Math (compiled with GWT) for SVD
